#pragma once
#include <cinttypes>
enum class Error : uint8_t {
  NO_ERROR = 0,
  READ_TIMESLOT_TIMEOUT = 1,
  WRITE_TIMESLOT_TIMEOUT = 2,
  WAIT_RESET_TIMEOUT = 3,
  VERY_LONG_RESET = 4,
  VERY_SHORT_RESET = 5,
  PRESENCE_LOW_ON_LINE = 6,
  READ_TIMESLOT_TIMEOUT_LOW = 7,
  AWAIT_TIMESLOT_TIMEOUT_HIGH = 8,
  PRESENCE_HIGH_ON_LINE = 9,
  INCORRECT_ONEWIRE_CMD = 10,
  INCORRECT_SLAVE_USAGE = 11,
  TRIED_INCORRECT_WRITE = 12,
  FIRST_TIMESLOT_TIMEOUT = 13,
  FIRST_BIT_OF_BYTE_TIMEOUT = 14,
  RESET_IN_PROGRESS = 15
};